version: "3.8"
services:
  db:
    image: postgres:latest

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5412:5432" # 外部ポートを5411に設定

